require('plugins.dep')
require('plugins.ui')
require('plugins.editor')
require('plugins.treesitter')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.git')
require('plugins.ai')
require('plugins.enhanced')

